---
language: ruby
cache: bundler
rvm: 
  # - 1.8.7
  - 1.9.3
  - 2.1.9
  - 2.3.1
  - 2.4.1
bundler_args: --without system_tests development
before_install:
  - bundle -v
  - rm Gemfile.lock || true
  - gem update --system
  - gem update bundler
  - gem --version
  - bundle -v
script: bundle exec rake test
sudo: false
env:
  - PUPPET_VERSION="~> 3.0" STRICT_VARIABLES="yes"
  - PUPPET_VERSION="~> 3.0" STRICT_VARIABLES="yes" FUTURE_PARSER="yes"
  - PUPPET_VERSION="~> 4.0" STRICT_VARIABLES="yes"
  - PUPPET_VERSION="~> 5.0" STRICT_VARIABLES="yes"
matrix:
  exclude:
  # - rvm: 1.8.7
  #   env: PUPPET_VERSION="~> 4.0" STRICT_VARIABLES="yes"
  - rvm: 1.9.3
    env: PUPPET_VERSION="~> 4.0" STRICT_VARIABLES="yes"
  - rvm: 1.9.3
    env: PUPPET_VERSION="~> 5.0" STRICT_VARIABLES="yes"
  - rvm: 2.3.1
    env: PUPPET_VERSION="~> 3.0" STRICT_VARIABLES="yes"
  - rvm: 2.3.1
    env: PUPPET_VERSION="~> 3.0" STRICT_VARIABLES="yes" FUTURE_PARSER="yes"
  - rvm: 2.4.1
    env: PUPPET_VERSION="~> 3.0" STRICT_VARIABLES="yes"
  - rvm: 2.4.1
    env: PUPPET_VERSION="~> 3.0" STRICT_VARIABLES="yes" FUTURE_PARSER="yes"
notifications:
  email:
    - fatmcgav@gmail.com
addons:
  code_climate:
    repo_token: 3c5a58e415766a086d4546e0bfa00feb8468f5a4927aa744c2c1d6a2be394f2f
