---
language: ruby
cache: bundler
rvm: 
  - 1.8.7
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2
bundler_args: --without development
before_install: rm Gemfile.lock || true
script: bundle exec rake test
sudo: false
env:
  - PUPPET_VERSION="~> 3.7.0"
  - PUPPET_VERSION="~> 3.7.0" PARSER="future"
  - PUPPET_VERSION="~> 3.8.0"
  - PUPPET_VERSION="~> 3.8.0" PARSER="future"
  - PUPPET_VERSION="~> 4.1.0"
  - PUPPET_VERSION="~> 4.2.0"
matrix:
  exclude:
  - rvm: 2.2
    env: PUPPET_VERSION="~> 3.7"
  - rvm: 2.2
    env: PUPPET_VERSION="~> 3.8"
notifications:
  email:
    - fatmcgav@gmail.com
addons:
  code_climate:
    repo_token: 3c5a58e415766a086d4546e0bfa00feb8468f5a4927aa744c2c1d6a2be394f2f
